[server]
fileWatcherType = "none"
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#6366F1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
font = "sans serif"
